openapi: 3.0.0
info:
title: Job-listing
description: Job-listing app API
version: 8.1.9

servers:
  - url:
    description: production server
  - url: http://localhost:3001/api
    description: local server
paths:
  /jobs:
    get:
      tags:
        - Jobs
      responses:
        '200':
          description: Successfully fetched
          content: 
            application/json:
              schema:
                type: array
                item:
                  type: string
